// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlat, TargetPlatform, defaultTargetPlatform, kIsWeb;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb3fQQoGp9sCdIhUp4zjx34cJ8jSvajWo',
    appId: '1:748006003177:android:12c08b838f4af148df7b78',
    messagingSenderId: '748006003177',
    projectId: 'job-search-85a2e',
    storageBucket: 'job-search-85a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW_hRc7IkrCQYvm3nmATKESOoQGRCLC8',
    appId: '1:748006003177:ios:d919e60637a57e8ddf7b78',
    messagingSenderId: '748006003177',
    projectId: 'job-search-85a2e',
    storageBucket: 'job-search-85a2e.appspot.com',
    iosClientId: '748006003177-3ai40fac4cgpk1katir71lu8v17iv2fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobSearch',
  );
}
